"""added zoom to favorites

Revision ID: 49b2f85a3c1e
Revises: a12ea55b0db0
Create Date: 2017-09-10 02:32:59.796272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b2f85a3c1e'
down_revision = 'a12ea55b0db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('zoom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'zoom')
    # ### end Alembic commands ###
